name: Regular base image update check
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      PROJECT_NAME: sabnzbd-rearchive
    steps:
      - uses: actions/checkout@v3

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: lscr.io/linuxserver/sabnzbd
          image: treyturner/$PROJECT_NAME

      - name: DockerHub login
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and tag
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$PROJECT_NAME:latest --tag $DOCKERHUB_USERNAME/$PROJECT_NAME:${{ github.run_number }}.${{ github.run_attempt }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Publish
        run: docker push --all-tags $DOCKERHUB_USERNAME/$PROJECT_NAME
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
