name: Build and publish

on:
  push:
    branches: [main]

env:
  PROJECT_NAME: sabnzbd-rearchive

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GitHub Container Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/$PROJECT_NAME:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/$PROJECT_NAME:${{ github.run_number }}.${{ github.run_attempt }}
            ghcr.io/${{ github.repository_owner }}/$PROJECT_NAME:latest
            ghcr.io/${{ github.repository_owner }}/$PROJECT_NAME:${{ github.run_number }}.${{ github.run_attempt }}
