name: Build and publish on base image update
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

env:
  PROJECT_NAME: sabnzbd-rearchive

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GitHub Container Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: ghcr.io/linuxserver/sabnzbd
          image: treyturner/${{ env.PROJECT_NAME }}
        env:
          DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

      - name: Build and push
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.run_number }}.${{ github.run_attempt }}
            ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ github.run_number }}.${{ github.run_attempt }}
