name: some manual action

on:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: 'treyturner'
          package-name: 'web-brogue'
          package-type: 'container'
          token: ${{ secrets.PAT }}